include parallelDefs

# required files
GLOBAL_REQUIRE = utils.h sequence.h graph.h graphColor.h graphColorOrdering.h graphUtils.h graphIO.h
LOCAL_REQUIRE = graphColorJP.h
OBJS = VertexColor.o graphColorJP.o graphColorOrdering.o

include ../common/timeRequiredFiles
include MakeBench

